name: "Build docs"

on:
    pull_request:
    push:

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ammaraskar/sphinx-action@master
              with:
                  docs-folder: "./"
                  build-command: "sphinx-build -nW --keep-going -b html -d _build/doctrees . _build/html"
            - uses: actions/upload-artifact@v1
              with:
                  name: DocumentationHTML
                  path: "_build/html"
